### ISSUE TITLE
setColor NullPointException

### ISSUE THREAD

**Issue by serkandyck** [lopspower/CircularFillableLoaders#1]
if i Set Fragment Return
java.lang.IllegalArgumentException: width and height must be > 0

Main Activity Return NullpointException All other cutomization code works setColor Getting error only

**Comment by lopspower** [comment]
It's possible to show your implementation of that?
I think setColor work well because the sample demo app use this. 

You need to used setColor with color integer this way :
`int color = Color.RED;`
or
`int color = Color.parseColor("#00ff00")`
and
`circularFillableLoaders.setColor(color);`

**Comment by serkandyck** [comment]
```
@Bind(R.id.loaderCpu)
CircularFillableLoaders  loaderCpu;

@Bind(R.id.loaderRam)
CircularFillableLoaders loaderRam;

@Bind(R.id.loaderSd)
CircularFillableLoaders loaderSd;
```

private void fillData() {

```
    long l = AppUtil.getAvailMemory(mContext);
    long y = AppUtil.getTotalMemory(mContext);
    final double x = (((y - l) / (double) y) * 100);
    loaderSd.setProgress((int) x);

    SDCardInfo mSDCardInfo = StorageUtil.getSDCardInfo();
    SDCardInfo mSystemInfo = StorageUtil.getSystemSpaceInfo(mContext);

    long nAvailaBlock;
    long TotalBlocks;
    if (mSDCardInfo != null) {
        nAvailaBlock = mSDCardInfo.free + mSystemInfo.free;
        TotalBlocks = mSDCardInfo.total + mSystemInfo.total;
    } else {
        nAvailaBlock = mSystemInfo.free;
        TotalBlocks = mSystemInfo.total;
    }

    final double percentStore = (((TotalBlocks - nAvailaBlock) / (double) TotalBlocks) * 100);


    capacity.setText(StorageUtil.convertStorage(TotalBlocks - nAvailaBlock) + "/" + StorageUtil.convertStorage(TotalBlocks));
    ram.setText(getUsageMemory() + "/" + getTotalRAM());
    loaderRam.setProgress((int) percentStore);
    loaderCpu.setColor(color);
```

Can i use all customization border, amplitude, progress but color get java.lang.IllegalArgumentException: width and height must be > 0

**Comment by serkandyck** [comment]
at com.mikhaellopez.circularfillableloaders.CircularFillableLoaders.updateWaveShader(CircularFillableLoaders.java:196)
                                                                                           at com.mikhaellopez.circularfillableloaders.CircularFillableLoaders.setColor(CircularFillableLoaders.java:306)
                                                                                           at com.androidcleaner.rambooster.fragment.MainFragment.fillData(MainFragment.java:124)
                                                                                           at com.androidcleaner.rambooster.fragment.MainFragment.onResume(MainFragment.java:80)

Maybe, Problem on Butterknife

**Comment by serkandyck** [comment]
if i put only <com.mikhaellopez.circularfillableloaders.CircularFillableLoaders and not any customization java code. Only XML Screenshot: http://prntscr.com/9dqll7 This Fragment Layout.

**Comment by serkandyck** [comment]
Problem on executing Code early and view's layout has not yet been measured by Android. i set timer and problem fixed. Sorry

**Comment by lopspower** [comment]
Cool, the goal is that you are a solution :+1:

**Comment by kiaanpillay** [comment]
I'm having the exact same issue. Please elaborate on how to fix
