### ISSUE TITLE
Fill percentage instead of Image

### ISSUE THREAD

**Issue by nhjariwala** [lopspower/CircularFillableLoaders#11]
First of all thanks a lot for this awesome library. 
How can I replace the image with fill percentage ?

Thanks

**Comment by lopspower** [comment]
If I understand your request, I think you just need to used a CircularImageView Library like this -> [https://github.com/lopspower/CircularImageView](https://github.com/lopspower/CircularImageView)
And add a RelativeLayout with TextView in center to show percentage.

**Comment by nhjariwala** [comment]
By using CircularImageView I will not get the wave filling effect... What I need is i need to display fill percentage of loader.
Any hint ?
